--
-- PostgreSQL database dump
--

\restrict UQKXIJxCYdWzD1g2LguG4aJV84pVRc36uKawI1KKFhyeMlxs7C0iUODrlspvI24

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-05-16 21:48:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5013 (class 1262 OID 16389)
-- Name: labguard; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE labguard WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE labguard OWNER TO postgres;

\unrestrict UQKXIJxCYdWzD1g2LguG4aJV84pVRc36uKawI1KKFhyeMlxs7C0iUODrlspvI24
\connect labguard
\restrict UQKXIJxCYdWzD1g2LguG4aJV84pVRc36uKawI1KKFhyeMlxs7C0iUODrlspvI24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16403)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id integer CONSTRAINT categories_category_id_not_null NOT NULL,
    name character varying(100) CONSTRAINT categories_category_name_not_null NOT NULL,
    description text
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16410)
-- Name: categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16411)
-- Name: equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment (
    id integer CONSTRAINT equipment_equipment_id_not_null NOT NULL,
    name character varying(150) CONSTRAINT equipment_equipment_name_not_null NOT NULL,
    category_id integer,
    model character varying(100),
    serial_number character varying(100) NOT NULL,
    location_id integer,
    status character varying(30) DEFAULT 'Available'::character varying NOT NULL,
    total_quantity integer NOT NULL,
    available_quantity integer NOT NULL,
    image_url text,
    description text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT equipment_available_quantity_check CHECK ((available_quantity >= 0)),
    CONSTRAINT equipment_status_check CHECK (((status)::text = ANY (ARRAY[('Available'::character varying)::text, ('In Use'::character varying)::text, ('Maintenance'::character varying)::text, ('Reserved'::character varying)::text]))),
    CONSTRAINT equipment_total_quantity_check CHECK ((total_quantity >= 0))
);


ALTER TABLE public.equipment OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16427)
-- Name: equipment_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipment_id_seq
    START WITH 1001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16428)
-- Name: equipment_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment_status_history (
    id integer CONSTRAINT equipment_status_history_history_id_not_null NOT NULL,
    equipment_id integer NOT NULL,
    old_status character varying(30),
    new_status character varying(30),
    changed_by integer,
    notes text,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT equipment_status_history_new_status_check CHECK (((new_status)::text = ANY (ARRAY[('Available'::character varying)::text, ('In Use'::character varying)::text, ('Maintenance'::character varying)::text, ('Reserved'::character varying)::text]))),
    CONSTRAINT equipment_status_history_old_status_check CHECK (((old_status)::text = ANY (ARRAY[('Available'::character varying)::text, ('In Use'::character varying)::text, ('Maintenance'::character varying)::text, ('Reserved'::character varying)::text])))
);


ALTER TABLE public.equipment_status_history OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16438)
-- Name: equipment_status_history_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_status_history_history_id_seq
    START WITH 1001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16439)
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    id integer CONSTRAINT locations_location_id_not_null NOT NULL,
    lab_name character varying(50) NOT NULL,
    section character varying(50),
    description text
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16446)
-- Name: locations_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16447)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id integer CONSTRAINT notifications_notification_id_not_null NOT NULL,
    user_id integer CONSTRAINT notifications_student_id_not_null NOT NULL,
    type character varying(20) NOT NULL,
    title character varying(150),
    message text,
    is_read boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    transaction_id integer,
    stage integer DEFAULT 0,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY (ARRAY[('success'::character varying)::text, ('warning'::character varying)::text, ('info'::character varying)::text, ('error'::character varying)::text])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16458)
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16459)
-- Name: reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports (
    id integer CONSTRAINT reports_report_id_not_null NOT NULL,
    generated_by integer,
    file_path text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.reports OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16466)
-- Name: reports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16467)
-- Name: return_details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.return_details (
    id integer CONSTRAINT return_details_return_id_not_null NOT NULL,
    transaction_id integer NOT NULL,
    condition_type character varying(20) NOT NULL,
    notes text
);


ALTER TABLE public.return_details OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16476)
-- Name: return_details_return_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.return_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_details_return_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16477)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer CONSTRAINT students_student_id_not_null NOT NULL,
    name character varying(100) CONSTRAINT students_student_name_not_null NOT NULL,
    email character varying(150) CONSTRAINT students_email_not_null NOT NULL,
    role character varying(30) CONSTRAINT students_role_not_null NOT NULL,
    department character varying(100),
    image_url text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    student_id character varying(10),
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16488)
-- Name: students_student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_student_id_seq
    START WITH 26001
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16489)
-- Name: system_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_logs (
    id integer CONSTRAINT system_logs_log_id_not_null NOT NULL,
    action character varying(150) NOT NULL,
    user_id integer,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) NOT NULL,
    CONSTRAINT system_logs_status_check CHECK (((status)::text = ANY (ARRAY[('Success'::character varying)::text, ('Failed'::character varying)::text])))
);


ALTER TABLE public.system_logs OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16497)
-- Name: system_logs_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_logs_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 16498)
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id integer CONSTRAINT transactions_transaction_id_not_null NOT NULL,
    equipment_id integer NOT NULL,
    user_id integer CONSTRAINT transactions_student_id_not_null NOT NULL,
    type character varying(20) NOT NULL,
    status character varying(30) DEFAULT 'Pending'::character varying NOT NULL,
    quantity integer NOT NULL,
    purpose text,
    request_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    approval_date timestamp without time zone,
    return_date timestamp without time zone,
    expected_return_date date,
    approved_by integer,
    notes text,
    CONSTRAINT transactions_quantity_check CHECK ((quantity > 0)),
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY (ARRAY[('Pending'::character varying)::text, ('Approved'::character varying)::text, ('Denied'::character varying)::text, ('Completed'::character varying)::text]))),
    CONSTRAINT transactions_type_check CHECK (((type)::text = ANY (ARRAY[('Borrow'::character varying)::text, ('Return'::character varying)::text])))
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16514)
-- Name: transactions_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4824 (class 2606 OID 16518)
-- Name: categories categories_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_category_name_key UNIQUE (name);


--
-- TOC entry 4826 (class 2606 OID 16520)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4828 (class 2606 OID 16522)
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);


--
-- TOC entry 4830 (class 2606 OID 16524)
-- Name: equipment equipment_serial_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_serial_number_key UNIQUE (serial_number);


--
-- TOC entry 4832 (class 2606 OID 16526)
-- Name: equipment_status_history equipment_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_status_history
    ADD CONSTRAINT equipment_status_history_pkey PRIMARY KEY (id);


--
-- TOC entry 4834 (class 2606 OID 16528)
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- TOC entry 4836 (class 2606 OID 16530)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 4838 (class 2606 OID 16532)
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- TOC entry 4817 (class 2606 OID 16628)
-- Name: return_details return_details_condition_type_check; Type: CHECK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE public.return_details
    ADD CONSTRAINT return_details_condition_type_check CHECK (((condition_type)::text = ANY (ARRAY[('excellent'::character varying)::text, ('good'::character varying)::text, ('fair'::character varying)::text, ('damaged'::character varying)::text]))) NOT VALID;


--
-- TOC entry 4840 (class 2606 OID 16534)
-- Name: return_details return_details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.return_details
    ADD CONSTRAINT return_details_pkey PRIMARY KEY (id);


--
-- TOC entry 4842 (class 2606 OID 16536)
-- Name: users students_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT students_email_key UNIQUE (email);


--
-- TOC entry 4844 (class 2606 OID 16538)
-- Name: users students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- TOC entry 4846 (class 2606 OID 16540)
-- Name: system_logs system_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_logs
    ADD CONSTRAINT system_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4848 (class 2606 OID 16542)
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 4818 (class 2606 OID 16627)
-- Name: users users_role_check; Type: CHECK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE public.users
    ADD CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY[('student'::character varying)::text, ('instructor'::character varying)::text, ('lab-assistant'::character varying)::text, ('admin'::character varying)::text]))) NOT VALID;


--
-- TOC entry 4849 (class 2606 OID 16558)
-- Name: equipment fk_equipment_categories; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT fk_equipment_categories FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;


--
-- TOC entry 4850 (class 2606 OID 16563)
-- Name: equipment fk_equipment_locations; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT fk_equipment_locations FOREIGN KEY (location_id) REFERENCES public.locations(id) ON DELETE SET NULL;


--
-- TOC entry 4851 (class 2606 OID 16568)
-- Name: equipment_status_history fk_equipment_status_history_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_status_history
    ADD CONSTRAINT fk_equipment_status_history_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE CASCADE;


--
-- TOC entry 4852 (class 2606 OID 16573)
-- Name: equipment_status_history fk_equipment_status_history_students; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_status_history
    ADD CONSTRAINT fk_equipment_status_history_students FOREIGN KEY (changed_by) REFERENCES public.users(id);


--
-- TOC entry 4853 (class 2606 OID 16615)
-- Name: notifications fk_notifications_transactions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notifications_transactions FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE SET NULL NOT VALID;


--
-- TOC entry 4854 (class 2606 OID 16620)
-- Name: notifications fk_notifications_users; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notifications_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4855 (class 2606 OID 16583)
-- Name: reports fk_reports_students; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fk_reports_students FOREIGN KEY (generated_by) REFERENCES public.users(id);


--
-- TOC entry 4856 (class 2606 OID 16588)
-- Name: return_details fk_return_details_transactions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.return_details
    ADD CONSTRAINT fk_return_details_transactions FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE CASCADE;


--
-- TOC entry 4857 (class 2606 OID 16593)
-- Name: system_logs fk_system_logs_students; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_logs
    ADD CONSTRAINT fk_system_logs_students FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4858 (class 2606 OID 16598)
-- Name: transactions fk_transactions_approved_by; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk_transactions_approved_by FOREIGN KEY (approved_by) REFERENCES public.users(id);


--
-- TOC entry 4859 (class 2606 OID 16603)
-- Name: transactions fk_transactions_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk_transactions_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE CASCADE;


--
-- TOC entry 4860 (class 2606 OID 16608)
-- Name: transactions fk_transactions_students; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk_transactions_students FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


-- Completed on 2026-05-16 21:48:01

--
-- PostgreSQL database dump complete
--

\unrestrict UQKXIJxCYdWzD1g2LguG4aJV84pVRc36uKawI1KKFhyeMlxs7C0iUODrlspvI24

